# Generated by Django 5.0.6 on 2024-07-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_Birthdate', models.DateField()),
                ('doctor_phone', models.CharField(max_length=15)),
                ('speciality', models.CharField(max_length=100)),
                ('doctor_address', models.TextField()),
                ('doctor_join_date', models.DateField()),
                ('doctor_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('doctor_nationality', models.CharField(choices=[('IN', 'Indian'), ('US', 'American'), ('UK', 'British')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctor')),
            ],
        ),
    ]
